name: Update Docker Hub Description

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update Docker HUB Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lacledeslan/gamesvr-ut99-freeplay
          short-description: "LL Unreal Tournament Dedicated Freeplay Server in Docker"
          readme-filepath: ./README.md
